# Project-wide Gradle settings.
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.vfs.watch=true
org.gradle.configuration-cache=true
org.gradle.workers.max=4

kotlin.incremental=true
ksp.incremental=true
ksp.incremental.intermodule=true

kotlin.code.style=official
android.nonTransitiveRClass=true
