name = "al-daftar-license-api"
main = "src/index.js"
compatibility_date = "2026-09-09"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "SMARTLEDGER_KV"
id = "c8f62e026ed645a8b7721b98d11e8809"

[limits]
cpu_ms = 10

