name = "al-daftar-license-api"
main = "src/index.ts"
compatibility_date = "2026-09-06"

[vars]
FIREBASE_PROJECT_ID = "al-daftar-android"
FIREBASE_PROJECT_NUMBER = "512516697236"
FIREBASE_APP_ID = "1:512516697236:android:2516cb9d724a44710c9881"

[[d1_databases]]
binding = "DB"
database_name = "al-daftar-license-db"
database_id = "76b6b20b-6780-4706-bc3c-e1a2c68a35bd"
migrations_dir = "migrations"
